export const ORDER_STATUSES = [
  'pending',
  'confirmed',
  'processing',
  'packed',
  'shipped',
  'out_for_delivery',
  'delivered',
  'cancelled',
  'returned',
  'refunded',
];

export const ORDER_STATUS_LABELS = {
  pending: 'Pending',
  confirmed: 'Confirmed',
  processing: 'Processing',
  packed: 'Packed',
  shipped: 'Shipped',
  out_for_delivery: 'Out for Delivery',
  delivered: 'Delivered',
  cancelled: 'Cancelled',
  returned: 'Returned',
  refunded: 'Refunded',
};

export const STATUS_BADGE_MAP = {
  pending: 'warning',
  confirmed: 'info',
  processing: 'primary',
  packed: 'primary',
  shipped: 'info',
  out_for_delivery: 'info',
  delivered: 'success',
  cancelled: 'danger',
  returned: 'secondary',
  refunded: 'dark',
  active: 'success',
  inactive: 'secondary',
  draft: 'secondary',
  paid: 'success',
  failed: 'danger',
};

export const NAV_ITEMS = [
  { path: '/', icon: 'bi-speedometer2', label: 'Dashboard' },
  { path: '/analytics', icon: 'bi-graph-up-arrow', label: 'Analytics' },
  { path: '/revenue', icon: 'bi-currency-rupee', label: 'Revenue' },
  { path: '/orders', icon: 'bi-bag-check', label: 'Orders' },
  { path: '/customers', icon: 'bi-people', label: 'Customers' },
  { path: '/products', icon: 'bi-box-seam', label: 'Products' },
  { path: '/categories', icon: 'bi-tags', label: 'Categories' },
  { path: '/brands', icon: 'bi-award', label: 'Brands & Sections' },
  { path: '/inventory', icon: 'bi-boxes', label: 'Inventory' },
  { path: '/coupons', icon: 'bi-ticket-perforated', label: 'Coupons' },
  { path: '/deliveries', icon: 'bi-truck', label: 'Deliveries' },
  { path: '/reports', icon: 'bi-file-earmark-bar-graph', label: 'Reports' },
  { path: '/banners', icon: 'bi-images', label: 'Banners' },
  { path: '/offer-strips', icon: 'bi-megaphone', label: 'Offers' },
  { path: '/blogs', icon: 'bi-journal-text', label: 'Blogs' },
  { path: '/faqs', icon: 'bi-question-circle', label: 'FAQs' },
  { path: '/notifications', icon: 'bi-bell', label: 'Notifications' },
  { path: '/visitors', icon: 'bi-eye', label: 'Visitors' },
  { path: '/settings', icon: 'bi-gear', label: 'Settings' },
  { path: '/doc', icon: 'bi-book', label: 'Doc' },
];
